import { BareMetalHost } from "@/types/bareMetal";

export const mockHosts: BareMetalHost[] = [
  {
    id: null,
    name: "f23a-r22-k8s6-mi-0002",
    serial_number: "AD48484",
    model: null,
    external_model_id: "1529",
    suppliers: [],
    unit: 49,
    status: "unknown",
    cpu_cores: 64,
    memory_mib: 256,
    storage_gb: 7500,
    available_cpu_cores: 2,
    available_memory_mib: 2400,
    available_storage_gb: 7000,
    baremetal_group: null,
    purchase_requisition: null,
    purchase_order: "44s83040",
    user: [],
    user_group: [],
    external_system_id: "1080",
    max_virtual_machine: -1,
    max_utilization: 1,
    labels: null,
    failure_zone: null,
    fab: "F23",
    phase: "1",
    data_center: "DC1",
    room: "R4",
    rack: "R22",
    as_number: 56040,
    os_template: "Ubuntu_22.04_SDA",
    ag: 3,
    pool: "F23",
    networks: {
      admin_network: {
        network_type: "admin",
        ip: "11.2.2.2",
        mac: "aa:bb:cc:dd:ee:ff",
        mask: "255.255.255.0",
        gateway: "11.2.2.1",
        vlan: "112",
      },
      provision_network: {
        network_type: "provision",
        ip: "192.168.2.2",
        mac: "aa:bb:cc:dd:ee:ff",
        mask: "255.255.255.0",
        gateway: null,
        vlan: null,
      },
    },
  },
  {
    id: null,
    name: "f23a-r22-k8s6-mi-0003",
    serial_number: "AD48485",
    model: "PowerEdge R750",
    external_model_id: "1529",
    suppliers: [],
    unit: 48,
    status: "active",
    cpu_cores: 64,
    memory_mib: 256,
    storage_gb: 7500,
    available_cpu_cores: 32,
    available_memory_mib: 128000,
    available_storage_gb: 4000,
    baremetal_group: null,
    purchase_requisition: "PR-2024-0012",
    purchase_order: "44s83041",
    user: ["alice"],
    user_group: ["k8s-team"],
    external_system_id: "1081",
    max_virtual_machine: -1,
    max_utilization: 1,
    labels: null,
    failure_zone: null,
    fab: "F23",
    phase: "1",
    data_center: "DC1",
    room: "R4",
    rack: "R22",
    as_number: 56041,
    os_template: "Ubuntu_22.04_SDA",
    ag: 3,
    pool: "F23",
    networks: {
      admin_network: {
        network_type: "admin",
        ip: "11.2.2.3",
        mac: "aa:bb:cc:dd:ee:01",
        mask: "255.255.255.0",
        gateway: "11.2.2.1",
        vlan: null,
      },
      provision_network: {
        network_type: "provision",
        ip: "192.168.2.3",
        mac: "aa:bb:cc:dd:ee:01",
        mask: "255.255.255.0",
        gateway: null,
        vlan: null,
      },
    },
  },
  {
    id: null,
    name: "f23a-r22-k8s6-mi-0004",
    serial_number: "AD48486",
    model: "PowerEdge R750",
    external_model_id: "1529",
    suppliers: [],
    unit: 47,
    status: "error",
    cpu_cores: 64,
    memory_mib: 256,
    storage_gb: 7500,
    available_cpu_cores: 0,
    available_memory_mib: 0,
    available_storage_gb: 7500,
    baremetal_group: null,
    purchase_requisition: null,
    purchase_order: "44s83042",
    user: [],
    user_group: [],
    external_system_id: "1082",
    max_virtual_machine: -1,
    max_utilization: 1,
    labels: null,
    failure_zone: null,
    fab: "F23",
    phase: "1",
    data_center: "DC1",
    room: "R5",
    rack: "R23",
    as_number: 56042,
    os_template: "Ubuntu_22.04_SDA",
    ag: 3,
    pool: "F23",
    networks: {
      admin_network: {
        network_type: "admin",
        ip: "11.2.2.4",
        mac: "aa:bb:cc:dd:ee:02",
        mask: "255.255.255.0",
        gateway: "11.2.2.1",
        vlan: null,
      },
      provision_network: {
        network_type: "provision",
        ip: "192.168.2.4",
        mac: "aa:bb:cc:dd:ee:02",
        mask: "255.255.255.0",
        gateway: null,
        vlan: null,
      },
    },
  },
];
